config/routes.rb
SizeCloset::Application.routes.draw do
  resources :closets
  devise_for :users
  root to: 'closets#index'

end

app/models/closet.rb
class Closet < ActiveRecord::Base
  belongs_to :user
  # has_many :stores
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :closet
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate_user!
end

app/controllers/closets_controller.rb
class ClosetsController < ApplicationController
  before_action :set_closet, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction

  def index
    @closets = Closet.order(sort_column + ' ' + sort_direction)
  end

  def show
  end

  def new
    @closet = Closet.new
  end

  def edit
  end

  def create
    @closet = Closet.new(closet_params)

    respond_to do |format|
      if @closet.save
        format.html { redirect_to @closet, notice: 'An item was added to your closet.' }
        format.json { render action: 'show', status: :created, location: @closet }
      else
        format.html { render action: 'new' }
        format.json { render json: @closet.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @closet.update(closet_params)
        format.html { redirect_to @closet, notice: 'Your item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @closet.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @closet.destroy
    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end

  private
  def set_closet
    @closet = Closet.find(params[:id])
  end

  def closet_params
    params.require(:closet).permit(:id, :user_id, :store, :category, :size, :style, :note)
  end

  def sort_column
    Closet.column_names.include?(params[:sort]) ? params[:sort] : "store"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = (column == sort_column) ? "current #{sort_direction}" : nil
    direction = column == params[:sort] && params[:direction] == "asc" ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/closets/_form.html.erb
<%= form_for(@closet) do |f| %>
  <% if @closet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@closet.errors.count, "error") %> prohibited this closet item from being saved:</h2>

      <ul>
      <% @closet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :store %><br>
    <%= f.text_field :store %>
  </div>
  <div>
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div>
    <%= f.label :style %><br>
    <%= f.text_field :style %>
  </div>
  <div>
    <%= f.label :size %><br>
    <%= f.text_field :size %>
  </div>
   <div>
    <%= f.label :note %><br>
    <%= f.text_area :note %>
  </div>
  <div class="btn-group">
    <%= f.submit %>
  </div>
<% end %>

app/views/closets/edit.html.erb
<h1>Edit a Closet Item</h1>

<%= render 'form' %>

<div class="links">
<%= link_to 'Show', @closet %> |
<%= link_to 'Back', closets_path %> |
<%= link_to 'Home', root_path %>
</div>

app/views/closets/index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th><%= sortable "store", "Store/Brand" %></th>
      <th><%= sortable "category" %></th>
      <th><%= sortable "style" %></th>
      <th><%= sortable "size" %></th>
      <th><%= sortable "note" %></th>
    </tr>
  </thead>

  <tbody class="table-body">
    <% @closets.each do |closet| %>
      <tr>
        <td><%= closet.store %></td>
        <td><%= closet.category %></td>
        <td><%= closet.style %></td>
        <td><%= closet.size %></td>
        <td><%= closet.note %></td>
        <div class="btn-group">
          <td><button type="button" class="btn btn-xs"><span class="glyphicon glyphicon-search"></span><%= link_to ' View', closet %></button></td>
        <!--   <td><button type="button" class="btn btn-xs"><span class="glyphicon glyphicon-pencil"></span><%= link_to ' Edit', edit_closet_path(closet) %></button></td> -->
          <td><button type="button" class="btn btn-xs"><span class="glyphicon glyphicon-trash"></span><%= link_to ' Delete', closet, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
        </div>
      </tr>
    <% end %>
  </tbody>
</table>

<button type="button" class="btn btn-xs"><span class="glyphicon glyphicon-plus"></span><%= link_to ' New Closet Item', new_closet_path %></button>

app/views/closets/new.html.erb
<h1>New Closet Item</h1>

<%= render 'form' %>

<div class="links">
<%= link_to 'Back', closets_path %>
</div>

app/views/closets/show.html.erb
<h3>Closet Item <%= @closet.id %> updated</h3>

<p>Store: <%= @closet.store %></p>

<p>Category: <%= @closet.category %></p>

<p>Style: <%= @closet.style %></p>

<p>Size: <%= @closet.size %></p>

<p>Notes: <%= @closet.note %></p>

<div class="links">
<%= link_to 'Edit', edit_closet_path(@closet) %> |
<%= link_to 'Delete', @closet, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Home', root_path %>
</div>

app/views/layouts/_login.html.erb
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
<% else %>
<!--   <%= link_to "Sign up", new_user_registration_path %> |
  <%= link_to "Sign in", new_user_session_path %> -->
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SizeCloset</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <link href='http://fonts.googleapis.com/css?family=Glass+Antiqua' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<body>

<h1>SizeCloset</h1>
<% if notice %>
  <p class="alert alert-notice"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-error"><%= alert %></p>
<% end %>

<div class='login'><%= render 'layouts/login' %></div>

<div class="container">
  <%= yield %>
</div>


</body>
</html>